name: Build and Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    name: Build Binary
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Build static binary
        run: |
          CGO_ENABLED=0 go build -ldflags="-s -w" -o systemd-healthcheck

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: systemd-healthcheck
          path: systemd-healthcheck

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: systemd-healthcheck
          path: .

      - name: Make binary executable
        run: chmod +x systemd-healthcheck

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: systemd-healthcheck
          generate_release_notes: true